<?php

?>
<ul class='main-nav'>
<!--     <li class='active'>-->
<!--		<a href="--><?php //echo $this->url('system') ?><!--">-->
<!--			<i class="icon-home"></i>-->
<!--			<span>Dashboard</span>-->
<!--		</a>-->
<!--	</li>-->
     <?php foreach ($this->container as $page): ?>
         <?php $Resources =$page->getResource();?>
         <?php $Resources =get_resource($Resources);?>

	<li <?php echo ($page->isActive() ? 'class="active"' : ''); ?>>
		<a href="<?php echo (count($page->pages))?"#":$page->getHref()?>" data-toggle="dropdown" class='dropdown-toggle'>
			<i class="icon-edit"></i>
			<span><?php echo $page->getLabel();?></span>
			<span class="caret"></span>
		</a>
         <?php if(!empty($page->pages)): ?>
		<ul class="dropdown-menu">
            <?php foreach($page->pages as $subpage):?>
                <?php
                $_resources = $subpage->getResource();
                $_permission = $subpage->getPermission();
                ?>
                <?php if($this->acl_check($_resources,$_permission)):?>
                    <li <?php echo ($subpage->isActive() ? 'class="active"' : ''); ?>>
                        <a href="<?php echo $subpage->getHref(); ?>"><?php echo $subpage->getLabel(); ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach;?>
		</ul>
        <?php endif;?>
	</li>
     <?php endforeach;?>
</ul>
