
            <div class="box">

				<div class="box-content nopadding">
					<div id="DataTables_Table_1_wrapper" class="dataTables_wrapper" role="grid"><table class="table table-nomargin table-bordered dataTable dataTable-noheader dataTable-nofooter" id="DataTables_Table_1">
						<thead>
							<tr role="row">
							<th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 267px;" aria-label="Rendering engine: activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Title')); ?></th>
							<th class="sorting_desc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 233px;" aria-sort="descending" aria-label="Browser: activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Slug')); ?></th>
							<th class="hidden-350 sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 40px;" aria-label="Platform(s): activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Active')); ?></th>
							<th class="hidden-1024 sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 60px;" aria-label="Engine version: activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Created at')); ?></th>
							<th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 60px;" aria-label="CSS grade: activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Updated at')); ?></th>
							
							<th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 40px;" aria-label="CSS grade: activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Action')); ?></th>
							</tr>
						</thead>
						
					<tbody role="alert" aria-live="polite" aria-relevant="all">
					<?php 
					$i=1;
					   foreach ($this->category as $val){
                        if($i%2!=0) $class='old';else  $class='even';
                    ?>
                           
    					   	<tr class='<?php echo $class;?>'>
                                <td class=''> <a style="color:#000000;" href="<?php echo $this->url('posts/category/edit', array('id' => $val->getId())); ?>" class="edit-line"><?php echo $this->escapeHtml($val->getTitle()); ?> </a></td>
                                <td class='sorting_1'> <a style="color:#000000;" href="<?php echo $this->url('posts/category/edit', array('id' => $val->getId())); ?>" class="edit-line"><?php echo $this->escapeHtml($val->getSlug()); ?></a></td>
                                <td class='hidden-350'><?php echo $this->escapeHtml($val->getActive()); ?></td>
                                <td class='hidden-1024'><?php echo $this->escapeHtml($val->getCreatedAt()); ?></td>
                                <td class='hidden-480'><?php echo $this->escapeHtml($val->getUpdatedAt()); ?></td>
                                <td class='hidden-480'>
                                 <a href="<?php echo $this->url('posts/category/edit', array('id' => $val->getId())); ?>" class="edit-line">
                                    <img src="#" alt="<?php echo $this->escapeHtml($this->translate('Edit')); ?>" />
                                </a>
                                |
                               <a href="<?php echo $this->url('posts/category/delete', array('id' => $val->getId())); ?>" class="delete-line">
                                    <img src="#" alt="<?php echo $this->escapeHtml($this->translate('Del')); ?>">
                                 </a>
                                </td>
                            </tr>
                          
                     <?php          
                     $i++;
					   }
					?>
						</tbody></table>
							<div class="dataTables_info" id="DataTables_Table_2_info">Showing <span>1</span> to <span>10</span> of <span>18</span> entries</div>
							<div class="dataTables_paginate paging_full_numbers" id="DataTables_Table_2_paginate"><a tabindex="0" class="first paginate_button paginate_button_disabled" id="DataTables_Table_2_first">First</a><a tabindex="0" class="previous paginate_button paginate_button_disabled" id="DataTables_Table_2_previous">Previous</a><span><a tabindex="0" class="paginate_active">1</a><a tabindex="0" class="paginate_button">2</a></span><a tabindex="0" class="next paginate_button" id="DataTables_Table_2_next">Next</a><a tabindex="0" class="last paginate_button" id="DataTables_Table_2_last">Last</a></div>	
							
					</div>
				</div>
				</div>