
            <div class="box">

				<div class="box-content nopadding">
					<div id="DataTables_Table_1_wrapper" class="dataTables_wrapper" role="grid"><table class="table table-nomargin table-bordered dataTable dataTable-noheader dataTable-nofooter" id="DataTables_Table_1">
						<thead>
							<tr role="row">
							<th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 267px;" aria-label="Rendering engine: activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Title')); ?></th>
							<th class="sorting_desc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 233px;" aria-sort="descending" aria-label="Browser: activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Slug')); ?></th>
							<th class="hidden-350 sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 40px;" aria-label="Platform(s): activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Active')); ?></th>
							<th class="hidden-1024 sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 60px;" aria-label="Engine version: activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Created at')); ?></th>
							<th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 60px;" aria-label="CSS grade: activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Updated at')); ?></th>
							
							<th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 40px;" aria-label="CSS grade: activate to sort column ascending"><?php echo $this->escapeHtml($this->translate('Action')); ?></th>
							</tr>
						</thead>
						
					<tbody role="alert" aria-live="polite" aria-relevant="all">
					<?php 
					$i=1;
					   foreach ($this->paginator as $val){
                        if($i%2!=0) $class='old';else  $class='even';
                    ?>
                           
    					   	<tr class='<?php echo $class;?>'>
                                <td class=''> <a style="color:#000000;" href="<?php echo $this->url('posts/category/edit', array('id' => $val['id'])); ?>" class="edit-line"><?php echo $this->escapeHtml($val['title']); ?> </a></td>
                                <td class='sorting_1'> <a style="color:#000000;" href="<?php echo $this->url('posts/category/edit', array('id' => $val['id'])); ?>" class="edit-line"><?php echo $this->escapeHtml($val['slug']); ?></a></td>
                                <td class='hidden-350'><?php echo $this->escapeHtml($val['active']); ?></td>
                                <td class='hidden-1024'><?php echo $this->escapeHtml($val['created_at']); ?></td>
                                <td class='hidden-480'><?php echo $this->escapeHtml($val['updated_at']); ?></td>
                                <td class='hidden-480'>
                                 <a href="<?php echo $this->url('posts/category/edit', array('id' => $val['id'])); ?>" class="edit-line">
                                    <img src="#" alt="<?php echo $this->escapeHtml($this->translate('Edit')); ?>" />
                                </a>
                                |
                               <a href="<?php echo $this->url('posts/category/delete', array('id' => $val['id'])); ?>" class="delete-line">
                                    <img src="#" alt="<?php echo $this->escapeHtml($this->translate('Del')); ?>">
                                 </a>
                                </td>
                            </tr>
                          
                     <?php          
                     $i++;
					   }
					?>
						</tbody></table>
                        <?php echo $this->paginationControl($this->paginator,
                            'Sliding',
                            'layout/system/paginator', array('route' => 'posts/category/default',
                                'order_by' => $order_by, 'order' => $order
                            ));
                        ?>
					</div>
				</div>
				</div>