<link rel="stylesheet" href="<?php echo $this->serverUrl("/temp/private/default/assets/css/plugins/xeditable/bootstrap-editable.css")?>">
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/bootbox/jquery.bootbox.js")?>"></script>
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/momentjs/jquery.moment.js")?>"></script>
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/mockjax/jquery.mockjax.js")?>"></script>
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/xeditable/bootstrap-editable.min.js")?>"></script>
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/xeditable/demo.js")?>"></script>
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/xeditable/address.js")?>"></script>

<div class="box">
    <div class="box-content nopadding">
        <div><table class="table table-nomargin table-bordered">
                <thead>
                    <tr role="row">
                        <th class="sorting"><?php echo $this->escapeHtml($this->translate('FullName')); ?></th>
                        <th class="sorting_desc"><?php echo $this->escapeHtml($this->translate('Group')); ?></th>
                        <th class="hidden-350 sorting"><?php echo $this->escapeHtml($this->translate('UserName')); ?></th>
                        <th class="hidden-1024 sorting"><?php echo $this->escapeHtml($this->translate('Created at')); ?></th>
                        <th class="hidden-480 sorting"><?php echo $this->escapeHtml($this->translate('Updated at')); ?></th>
                        <th class="hidden-480 sorting"><?php echo $this->escapeHtml($this->translate('Action')); ?></th>
                    </tr>
                </thead>
                <tbody role="alert" aria-live="polite" aria-relevant="all">
                <?php
                $i=1;
                foreach($this->paginator as $val){
                    $class = ($i%2!=0)?'old':'even';
                   // var_dump($val->getFullname());
                    ?>

                    <tr class='<?php echo $class;?>'>
                        <td class=''>
                            <a style="color:#000000;" href="<?php echo $this->url('user/user-manager', array('action'=>'edit','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="edit-line">
                                <?php echo $val['fullname']; ?>
                            </a>


                        </td>

                        <?php $role = \User\Libs\Role\Model::fromId($val['user_acl_role_id'])?>
                        <td class='sorting_1'>
                            <a href="#"
                               id="sex1"
                               data-type="select"
                               data-pk="<?php echo $val['id']?>"
                               data-value=""
                               data-original-title="Select sex"
                               class="editable editable-click editable-open"
                               style="color: gray;"><?php echo $role->getName();?></a>
                        </td>
                        <td class='hidden-350'><?php echo $this->escapeHtml($val['username']); ?></td>
                        <td class='hidden-1024'><?php echo $this->escapeHtml($val['created_at']); ?></td>
                        <td class='hidden-480'><?php  echo $this->escapeHtml($val['updated_at']); ?></td>
                        <td class='hidden-480'>
                            <a href="<?php echo $this->url('user/user-manager', array('action'=>'edit','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="edit-line">
                                <button class="btn btn-danger"> <i class="icon-edit"></i></button>
                            </a>

                            <a href="<?php echo $this->url('user/user-manager', array('action'=>'delete','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="delete-line">
                                <button class="btn btn-danger"> <i class="icon-trash"></i></button>
                            </a>
                        </td>
                    </tr>

                    <?php
                    $i++;
                }
                ?>
                </tbody></table>
<!--            <div class="dataTables_info" id="DataTables_Table_2_info">Showing <span>1</span> to <span>10</span> of <span>18</span> entries</div>-->
<!--            <div class="dataTables_paginate paging_full_numbers" id="DataTables_Table_2_paginate">-->
                <?php echo $this->paginationControl($this->paginator,
                    'Sliding',
                    'layout/system/paginator', array('route' => 'user/user-manager'));
                ?>
<!--            </div>-->

        </div>
    </div>
</div>
<script type="text/javascript">
        $('#sex1').editable({
            url: '<?php echo $this->url('user/user-manager',array('action'=>'ajax'));?>',
            prepend: "not selected",
            source: <?php
                     $user = new \User\Libs\Role\Collection();
                     echo "[";
                     $html="";
                     foreach($user->getRoles() as $row){
                        $html .= '{value:'.$row->getId().',text:"'.$row->getName().'"},';
                     }
                     echo substr($html,0,-1);
                     echo "]";
            ?>,
            display: function(value, sourceData) {
                var colors = {"": "gray", 1: "green", 2: "blue"},
                    elem = $.grep(sourceData, function(o){return o.value == value;});

                if(elem.length) {
                    $(this).text(elem[0].text).css("color", colors[value]);
                } else {
                    $(this).empty();
                }
            },
            success:function(data){
                console.log(data);
            }
        });
</script>