<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Posts\Module'                        => __DIR__ . '/Module.php',
    'Posts\Controller\IndexController'    => __DIR__ . '/src/Posts/Controller/IndexController.php',
    'Posts\Controller\CategoryController' => __DIR__ . '/src/Posts/Controller/CategoryController.php',
);
