<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('FrontEnd'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/temp/front/default/assets/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/temp/front/default/assets/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/temp/front/default/assets/css/style.css')
                        ->prependStylesheet($this->basePath() . '/temp/front/default/assets/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/temp/front/default/assets/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/temp/front/default/assets/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/temp/front/default/assets/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    
                    <a class="brand" href="<?php echo $this->url('front') ?>"><?php echo $this->translate('FrontEnd') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('front') ?>"><?php echo $this->translate('Home') ?></a></li>
                            
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-list"></span> Posts<b class="caret"></b></a>
                              <ul class="dropdown-menu">
                                <li><a href="#"><?php echo $this->translate('Article') ?></a></li>
                                <li><a href="#"><?php echo $this->translate('Category') ?></a></li>                               
                              </ul>
                            </li> 
                        </ul>
                        
                        <ul  class="nav navbar-right" style="float: right;">
                            <li><a href="<?php echo $this->url('system') ?>"><?php echo $this->translate('BackEnd') ?></a></li>
                        </ul>
                        
                        
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
