<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title> DEMO </title>
<script type="text/javascript" src="/assets/backend/system/upload-file/assets/jquery.js"></script>
<script type="text/javascript" src="/assets/backend/system/upload-file/assets/jquery-ui.js"></script>
<script type="text/javascript" src="/assets/backend/system/upload-file/assets/tooltip.js"></script>
<script type="text/javascript" src="/assets/backend/system/upload-file/assets/global.js"></script>
<link href="/assets/backend/system/upload-file/assets/redmond/jquery-ui.css" rel="stylesheet" type="text/css" />
<link href="/assets/backend/system/upload-file/filemanager/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="msgholder"></div>
<span id="loader"></span>
<div id="maindata"></div>
<div id="dialog-confirm-single-delete" style="display:none;" title="Delete File">
  <p>
    <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
    
  </p>
</div>
<div id="dialog-confirm-create-dir" style="display:none;" title="Create Directory">
  <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Enter your new directory name <span style="display:block; margin-top:5px; text-align:center">
    <input name="dirname" type="text" class="inputbox" id="dirname" size="20" />
    </span></p>
</div>
<script type="text/javascript">
// <![CDATA[
  $('a.getfile').live('click', function () {
	  (opener?opener:openerWin).setAssetValue('<?php echo URL_WEB;?>/uploads/' + $(this).attr('rel'));
	  self.closeWin();
  });
$(document).ready(function () {
  $(".thumbview").live({
	mouseenter: function() { 
	  $(this).find("p.control").fadeIn(200);
	},
	mouseleave: function () {
	  $(this).find("p.control").fadeOut(400);
	}
  });

    function showLoader() {
        $('#loader').fadeIn(200);
    }

    function hideLoader() {
        $('#loader').fadeOut(200);
    };

    function loadList(dirdata) {
        showLoader();
        $.ajax({
            type: 'post',
            url: "<?php echo $this->url('system/filemanager',array('action'=>'ajax'),array('force_canonical' => true));?>",
            data: 'rel_dir=' + dirdata,
            cache: false,
            success: function (html) {
                $("#maindata").html(html);
            }
        });
        hideLoader();
    }

    loadList('');
	
    $('a.dirchange').live('click', function (e) {
        e.preventDefault();
        var dirdata = escape($(this).attr('id'))
        showLoader();
        $.ajax({
            type: 'post',
            url: "<?php echo $this->url('system/filemanager',array('action'=>'ajax'),array('force_canonical' => true));?>",
            data: 'rel_dir=' + dirdata,
            cache: false,
            success: function (html) {
                $("#maindata").html(html);
            }
			
        });
        hideLoader();
    });

    // Delete single file/folder
    $('a.del-single').live('click', function () {
        var id = $(this).attr('id')
        var parent = $(this).parent().parent();
        var title = $(this).attr('rel');
        $("#dialog-confirm-single-delete").data({
            'delid': id,
            'parent': parent,
            'title': title
        }).dialog('open');
        return false;
    });
    $("#dialog-confirm-single-delete").dialog({
        resizable: false,
        bgiframe: true,
        autoOpen: false,
        width: 400,
        height: "auto",
        zindex: 9998,
        modal: false,
        buttons: {
            'Delete': function () {
                var parent = $(this).data('parent');
                var id = $(this).data('delid');
                var title = $(this).data('title');
				var path = id + title;

                $.ajax({
                    type: 'post',
                    url: "<?php echo $this->url('system/filemanager',array('action'=>'ajax'),array('force_canonical' => true));?>",
                    data: 'fmaction=deleteSingle&path=' + path + '&name=' + title,
                    beforeSend: function () {
                        parent.animate({
                            'backgroundColor': '#FFBFBF'
                        }, 400);
                    },
                    success: function (res) {
                        parent.fadeOut(400, function () {
                            parent.remove();
                        });
                        $("#msgholder").html(res);
                    }
                });

                $(this).dialog('close');
            },
            'CANCEL': function () {
                $(this).dialog('close');
            }
        }
    });
	
	
    // Create Directory
    $('a#create-dir').live('click', function () {
        var id = $(this).attr('rel');
        $("#dialog-confirm-create-dir").data({
            'id': id
        }).dialog('open');
        return false;
    });

    $("#dialog-confirm-create-dir").dialog({
        resizable: false,
        bgiframe: true,
        autoOpen: false,
        width: 400,
        height: "auto",
        zindex: 9998,
        modal: false,
        buttons: {
            'Create': function () {
                var id = $(this).data('id');
				var title = $("#dirname").val();
				var path = id;
	
				var str = 'fmaction=createDir';
					str +=  '&path=' + path;
					str +=  '&name=' + title;
				console.log(str);		
                $.ajax({
                    type: 'post',
                    url: "<?php echo $this->url('system/filemanager',array('action'=>'ajax'),array('force_canonical' => true));?>",
                    data: str,
					success: function (res) {
						$("#msgholder").html(res);
						setTimeout(function () {
							$(loadList(id)).fadeIn("slow");
						}, 2000);
					}
                });

                $(this).dialog('close');
            },
            'CANCEL': function () {
                $(this).dialog('close');
            }
        }
    });
	
	// File Upload
	$('#fileupload').live('click', function () {
		var id = $(this).attr('rel');
        alert(id);
		$('#admin_form').ajaxSubmit({
			target: "#msgholder",
			url: "<?php echo $this->url('system/filemanager',array('action'=>'ajax'),array('force_canonical' => true));?>",
			clearForm: 1,
			data: {
				fmaction: "uploadFile"
			},
			success: function (res) {
            
			  setTimeout(function () {
				  $(loadList(id)).fadeIn("slow");
			  }, 2000);
			}
		});
		return false;
	});
});
// ]]>
</script>
</body>
</html>