
<div class="box">
    <div class="box-content nopadding">
        <div id="DataTables_Table_1_wrapper" class="dataTables_wrapper" role="grid"><table class="table table-nomargin table-bordered dataTable dataTable-noheader dataTable-nofooter" id="DataTables_Table_1">
                <thead>
                    <tr role="row">
                        <th class="sorting"><?php echo $this->escapeHtml($this->translate('ID')); ?></th>
                        <th class="sorting_desc"><?php echo $this->escapeHtml($this->translate('Name')); ?></th>
                        <th class="hidden-350 sorting"><?php echo $this->escapeHtml($this->translate('Description')); ?></th>
                    </tr>
                </thead>
                <tbody role="alert" aria-live="polite" aria-relevant="all">
                <?php
                $i=1;
                foreach($this->paginator as $val){
                    $class = ($i%2!=0)?'old':'even';
                    // var_dump($val->getFullname());
                    ?>
                    <tr class='<?php echo $class;?>'>
                        <td class=''>
                            <a style="color:#000000;" href="<?php echo $this->url('user/role-manager', array('action'=>'edit','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="edit-line">
                                <?php echo $val['name']; ?>
                            </a>
                        </td>
                        <td class='hidden-350'><?php echo $this->escapeHtml($val['description']); ?></td>
                        <td class='hidden-480'>
                            <a href="<?php echo $this->url('user/role-manager', array('action'=>'edit','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="edit-line">
                                <button class="btn btn-danger"> <i class="icon-edit"></i></button>
                            </a>

                            <a href="<?php echo $this->url('user/role-manager', array('action'=>'delete','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="delete-line">
                                <button class="btn btn-danger"> <i class="icon-trash"></i></button>
                            </a>
                        </td>
                    </tr>

                    <?php
                    $i++;
                }
                ?>
                </tbody></table>
            <div class="dataTables_info" id="DataTables_Table_2_info">Showing <span>1</span> to <span>10</span> of <span>18</span> entries</div>
            <div class="dataTables_paginate paging_full_numbers" id="DataTables_Table_2_paginate"><a tabindex="0" class="first paginate_button paginate_button_disabled" id="DataTables_Table_2_first">First</a><a tabindex="0" class="previous paginate_button paginate_button_disabled" id="DataTables_Table_2_previous">Previous</a><span><a tabindex="0" class="paginate_active">1</a><a tabindex="0" class="paginate_button">2</a></span><a tabindex="0" class="next paginate_button" id="DataTables_Table_2_next">Next</a><a tabindex="0" class="last paginate_button" id="DataTables_Table_2_last">Last</a></div>

        </div>
    </div>
</div>