<link rel="stylesheet" href="<?php echo $this->serverUrl("/temp/private/default/assets/css/plugins/xeditable/bootstrap-editable.css")?>">
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/bootbox/jquery.bootbox.js")?>"></script>
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/momentjs/jquery.moment.js")?>"></script>
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/mockjax/jquery.mockjax.js")?>"></script>
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/xeditable/bootstrap-editable.min.js")?>"></script>
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/xeditable/demo.js")?>"></script>
<script src="<?php echo $this->serverUrl("/temp/private/default/assets/js/plugins/xeditable/address.js")?>"></script>
<div class="box">
    <div class="box-content nopadding">
        <div class="dataTables_wrapper" role="grid"><table class="table table-nomargin table-bordered">
                <thead>
                    <tr role="row">
                        <th class="sorting"><?php echo $this->escapeHtml($this->translate('Id')); ?></th>
                        <th class="sorting"><?php echo $this->escapeHtml($this->translate('Name')); ?></th>
                        <th class="sorting_desc"><?php echo $this->escapeHtml($this->translate('Des')); ?></th>
                        <th class="hidden-350 sorting"><?php echo $this->escapeHtml($this->translate('Action')); ?></th>
                    </tr>
                </thead>
                <tbody role="alert" aria-live="polite" aria-relevant="all">
                <?php
                $i=1;
                foreach($this->paginator as $val){
                    $class = ($i%2!=0)?'old':'even';
                ?>
                <tr class='<?php echo $class;?>'>
                        <td><?php echo $val['id'];?></td>
                        <td class=''>
                            <a style="color:#000000;" href="<?php echo $this->url('user/role-manager', array('action'=>'edit','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="edit-line">
                                <?php echo $val['name']; ?>
                            </a>
                        </td>
                        <td class='hidden-350'>
                            <a href="#" id="description_<?php echo $val['id'];?>"
                                data-type="text"
                                data-pk="<?php echo $val['id'];?>"
                                data-original-title="Enter username"
                                class="editable editable-click"> <?php echo $this->escapeHtml($val['description']); ?></a>
                                <script type="text/javascript">
                                    $('#description_<?php echo $val['id'];?>').editable({
                                        url:'<?php echo $this->url('user/role-manager',array('action'=>'ajax'));?>',
                                        type: 'text',
                                        name: 'description',
                                        title: 'Enter username',
                                        success:function(data){
                                            console.log(data);
                                        }
                                    });
                                </script>
                        </td>
                        <td class='hidden-480'>
                            <a href="<?php echo $this->url('user/role-manager', array('action'=>'edit','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="edit-line">
                                <button class="btn btn-danger"> <i class="icon-edit"></i></button>
                            </a>

                            <a href="<?php echo $this->url('user/role-manager', array('action'=>'delete','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="delete-line">
                                <button class="btn btn-danger"> <i class="icon-trash"></i></button>
                            </a>
                        </td>
                 </tr>
                <?php
                    $i++;
                  }
                ?>
                </tbody>
            </table>
            <?php echo $this->paginationControl($this->paginator,
                    'Sliding',
                    'layout/system/paginator', array('route' => 'user/role-manager', 'order_by' => $order_by, 'order' => $order));
            ?>
        </div>
    </div>
</div>