<!doctype html>
<html>
<head>
	<meta charset="utf8">
	<?php echo $this->headTitle('MDS '. $this->translate('BackEnd'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
   <!-- Apple devices fullscreen -->
    <?php echo $this->headMeta()->appendName('apple-mobile-web-app-capable', 'yes')?>
    <!-- Apple devices fullscreen -->  
    <?php echo $this->headMeta()->appendName('apple-mobile-web-app-status-bar-style', 'black-translucent') ?>

    <!-- Bootstrap styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/temp/private/default/assets/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/temp/private/default/assets/css/style.css')
                    ->prependStylesheet($this->basePath() . '/temp/private/default/assets/css/plugins/jquery-ui/smoothness/jquery.ui.theme.css')
                    ->prependStylesheet($this->basePath() . '/temp/private/default/assets/css/plugins/jquery-ui/smoothness/jquery-ui.css')
                    ->prependStylesheet($this->basePath() . '/temp/private/default/assets/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/temp/private/default/assets/css/plugins/datatable/TableTools.css')
                    ->prependStylesheet($this->basePath() . '/temp/private/default/assets/css/plugins/chosen/chosen.css')
                    ->prependStylesheet($this->basePath() . '/temp/private/default/assets/css/bootstrap.min.css') ?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/demonstration.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/application.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/eakroko.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/fullcalendar/fullcalendar.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/pageguide/jquery.pageguide.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/imagesLoaded/jquery.imagesloaded.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/flot/jquery.flot.resize.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/flot/jquery.flot.pie.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/flot/jquery.flot.bar.order.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/flot/jquery.flot.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/bootbox/jquery.bootbox.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/vmap/jquery.vmap.sampledata.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/vmap/jquery.vmap.world.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/vmap/jquery.vmap.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/slimscroll/jquery.slimscroll.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/touch-punch/jquery.touch-punch.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/jquery-ui/jquery.ui.resizable.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/jquery-ui/jquery.ui.draggable.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/jquery-ui/jquery.ui.mouse.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/jquery-ui/jquery.ui.widget.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/plugins/jquery-ui/jquery.ui.core.min.js')
        ->prependFile($this->basePath() . '/temp/private/default/assets/js/jquery.min.js')
    ; ?>
	<!-- Apple devices Homescreen icon -->
	<link rel="apple-touch-icon-precomposed" href="<?php echo $this->basePath();?>/temp/private/default/assets/img/apple-touch-icon-precomposed.png" />

</head>

<body>
	<div id="navigation">
        <?php //echo $this->partial('navigation');?>

        <div class="container-fluid">
            <a href="#" id="brand">MDS</a>
            <a href="#" class="toggle-nav" rel="tooltip" data-placement="bottom" title="Toggle navigation"><i class="icon-reorder"></i></a>

            <?php echo $this->navigation('Navbar')->menu()->setAcl($this->acl())->setRole($this->user_system()->getRole()->getName())
            ->setPartial('layout/system/navbar')->render();
        ?>
            <div class="user">
                <!--  --><ul class="icon-nav">
                    <li class="dropdown sett">
                        <a href="#" class='dropdown-toggle' data-toggle="dropdown"><i class="icon-cog"></i></a>
                        <ul class="dropdown-menu pull-right theme-settings">
                            <li>
                                <span>Layout-width</span>
                                <div class="version-toggle">
                                    <a href="#" class='set-fixed'>Fixed</a>
                                    <a href="#" class="active set-fluid">Fluid</a>
                                </div>
                            </li>
                            <li>
                                <span>Topbar</span>
                                <div class="topbar-toggle">
                                    <a href="#" class='set-topbar-fixed'>Fixed</a>
                                    <a href="#" class="active set-topbar-default">Default</a>
                                </div>
                            </li>
                            <li>
                                <span>Sidebar</span>
                                <div class="sidebar-toggle">
                                    <a href="#" class='set-sidebar-fixed'>Fixed</a>
                                    <a href="#" class="active set-sidebar-default">Default</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class='dropdown colo'>
                        <a href="#" class='dropdown-toggle' data-toggle="dropdown"><i class="icon-tint"></i></a>
                        <ul class="dropdown-menu pull-right theme-colors">
                            <li class="subtitle">
                                Predefined colors
                            </li>
                            <li>
                                <span class='red'></span>
                                <span class='orange'></span>
                                <span class='green'></span>
                                <span class="brown"></span>
                                <span class="blue"></span>
                                <span class='lime'></span>
                                <span class="teal"></span>
                                <span class="purple"></span>
                                <span class="pink"></span>
                                <span class="magenta"></span>
                                <span class="grey"></span>
                                <span class="darkblue"></span>
                                <span class="lightred"></span>
                                <span class="lightgrey"></span>
                                <span class="satblue"></span>
                                <span class="satgreen"></span>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="more-locked.html" class='lock-screen' rel='tooltip' title="Lock screen" data-placement="bottom"><i class="icon-lock"></i></a>
                    </li>
                </ul>
                <div class="dropdown">
                    <a href="#" class='dropdown-toggle' data-toggle="dropdown">
                        <?php echo $this->user_system()->getFullname()?>
                        <img src="<?php echo $this->basePath() . '/temp/private/default/assets/';?>img/demo/user-avatar.jpg" alt="">
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="more-userprofile.html">Edit profile</a>
                        </li>
                        <li>
                            <a href="#">Account settings</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('user/logout');?>">Sign out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
	</div><!-- end-navigation -->
	<div class="container-fluid" id="content">
		<div id="left">
            <form action="http://www.eakroko.de/flat/search-results.html" method="GET" class='search-form'>
                <div class="search-pane">
                    <input type="text" name="search" placeholder="Search here...">
                    <button type="submit"><i class="icon-search"></i></button>
                </div>
            </form>
            <?php //echo $this->partial('menuleft');?>
            <?php $module = empty($this->routeParams['module']) ? null : strtolower($this->routeParams['module']); ?>
            <?php echo $this->partial($module . '-menu.phtml', array('treeview' => $this->treeview, 'moduleMenu' => $this->moduleMenu)); ?>
		</div><!-- end-left -->

        <?php //echo "102"; var_dump($this->routeParams);?>
		<div id="main">
			<div class="container-fluid">
				<div class="page-header">
                    <?php //echo $this->partial('pageheader');?>
				</div><!-- end-page-header -->
				<div class="breadcrumbs">
                    <?php $partial = array('breadcrumbs', 'default') ?>
                    <?php $this->navigation('Navbar')->breadcrumbs()->setPartial($partial) ?>
                    <?php echo $this->navigation('Navbar')->breadcrumbs()->render() ?>
                    <?php //echo $this->navigation('Navbar')->breadcrumbs()->setMinDepth(0)->setPartial('breadcrumbs'); ?>
                    <?php //echo $this->partial('breadcrumbs');?>

				</div><!-- end-breadcrumbs -->
				<?php echo $this->partial('messages', array('messages' => $this->flashMessages)); ?>
				<div class="row-fluid">
					<div class="span12">
					<p>
						<?php echo $this->content; ?>
					</div>
				</div><!-- end-row-fluid -->
			</div>
		</div>
	</div>
	</body>

	</html>

