<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-title">
                <h3>
                    <i class="icon-table"></i>
                    Colored header
                </h3>
            </div>
            <div class="box-content nopadding">
                <table class="table table-nomargin table-colored-header">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th class="hidden-350">Slug(s)</th>
                        <th class="hidden-1024">Status</th>
                        <th class="hidden-480">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($this->lists as $row):?>
                        <?php print_r($row);?>
                    <tr>
                        <td><?php echo $row['id'];?></td>
                        <td><?php echo $row['name'];?></td>
                        <td class="hidden-350"><?php echo $row['slug']?></td>
                        <td class="hidden-1024"><?php echo $this->isCheck($row['active']);?></td>
                        <td class="hidden-480">X</td>
                    </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>