<ul class="nav nav-list">
    <li class="open active">
        <a href="#">
            <i class="glyphicon glyphicon-edit"></i>
            <span class="menu-text"><?php echo $this->escapeHtml($this->translate('category')); ?> News</span>
        </a>
        <ul class="submenu">
            <li class="active">
                <a href="<?php echo $this->url('module/category'); ?>">
                    <?php echo $this->escapeHtml($this->translate('Documents list')); ?>
                </a>
            </li>
        </ul>
    </li>
</ul>
