<div class="subnav">
    <div class="subnav-title">
        <a href="#" class="toggle-subnav"><i class="icon-angle-down"></i><span>Users</span></a>
    </div>
    <ul class="subnav-menu">
        <li>
            <a href="#">Articles</a>
        </li>
        <li>
            <a href="#">News</a>
        </li>
        <li>
            <a href="#">Pages</a>
        </li>
        <li>
            <a href="#">Comments</a>
        </li>
    </ul>
</div>