<div class="box">
    <div class="box-content nopadding">
        <div>
            <table class="table table-nomargin table-bordered">
                <thead>
                <tr role="row">
                    <th class="sorting"><?php echo $this->escapeHtml($this->translate('ID')); ?></th>
                    <th class="sorting_desc"><?php echo $this->escapeHtml($this->translate('Title')); ?></th>
                    <th class="hidden-350 sorting"><?php echo $this->escapeHtml($this->translate('Created At')); ?></th>
                    <th class="hidden-350 sorting"><?php echo $this->escapeHtml($this->translate('Update At')); ?></th>
                    <th class="hidden-350 sorting"><?php echo $this->escapeHtml($this->translate('Action')); ?></th>
                </tr>
                </thead>
                <tbody role="alert" aria-live="polite" aria-relevant="all">
                <?php
                $i=1;
                foreach($this->paginator as $val){
                    $class = ($i%2!=0)?'old':'even';
                    ?>
                    <tr class='<?php echo $class;?>'>
                        <td>
                            <?php echo $val['id'];?>
                        </td>
                        <td class=''>
                            <a style="color:#000000;" href="<?php echo $this->url('user/permission-manager', array('action'=>'edit','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="edit-line">
                                <?php echo $val['title'];?>
                            </a>
                        </td>

                        <td class='hidden-350'><?php echo $val['created_at']; ?></td>
                        <td class='hidden-350'><?php echo $val['updated_at']; ?></td>
                        <td class='hidden-480'>
                            <a href="<?php echo $this->url('posts/articles/default', array('action'=>'edit','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="edit-line">
                                <button class="btn btn-danger"> <i class="icon-edit"></i></button>
                            </a>

                            <a href="<?php echo $this->url('posts/articles/default', array('action'=>'delete','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="delete-line">
                                <button class="btn btn-danger"> <i class="icon-trash"></i></button>
                            </a>
                        </td>
                    </tr>
                    <?php
                    $i++;
                }
                ?>
                </tbody>
            </table>
            <?php echo $this->paginationControl($this->paginator,
                'Sliding',
                'layout/system/paginator', array('route' => 'posts/articles/default', 'order_by' => $order_by, 'order' => $order));
            ?>
        </div>
    </div>
</div>