<div class="span12">
	<div class="box">
		<div class="box-title">
			<h3>
				<i class="icon-reorder"></i>
				Widget
			</h3>
		</div>
		<div class="box-content">
            <?php foreach ($this->customeWidgets as $widget): ?>
                <?php if (empty($widget['id']) or empty($widget['title']) or empty($widget['content'])): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <div class="widget-box" id="<?php echo $this->escapeHtml(!empty($widget['id']) ? $widget['id'] : ''); ?>">
                    <div class="widget-header">
                        <span><?php echo $this->escapeHtml($this->translate(!empty($widget['title']) ? $widget['title'] : '')); ?></span>
                    </div>
                    <div class="widget-body">
                        <?php echo !empty($widget['content']) ? $widget['content'] : ''; ?>
                    </div>
                </div>
            <?php endforeach; ?>
		</div>
	</div>
</div>