<table class="table clickable table-striped table-hover">
    <colgroup>
        <col width="90%">
        <col width="10%">
    </colgroup>
    <thead>
        <tr>
            <th><?php echo $this->escapeHtml($this->translate('Name')); ?></th>
            <th class="text-center"><?php echo $this->escapeHtml($this->translate('Edit')); ?></th>
        </tr>
    </thead>
    <tbody>

    </tbody>
</table>
