<div class="box">
    <div class="box-content nopadding">
        <div>
            <table class="table table-nomargin table-bordered">
                <thead>
                <tr role="row">
                    <th class="sorting"><?php echo $this->escapeHtml($this->translate('ID')); ?></th>
                    <th class="sorting_desc"><?php echo $this->escapeHtml($this->translate('Permission')); ?></th>
                    <th class="hidden-350 sorting"><?php echo $this->escapeHtml($this->translate('Resource')); ?></th>
                    <th class="hidden-350 sorting"><?php echo $this->escapeHtml($this->translate('Action')); ?></th>
                </tr>
                </thead>
                <tbody role="alert" aria-live="polite" aria-relevant="all">
                <?php
                $i=1;
                foreach($this->paginator as $val){
                    $class = ($i%2!=0)?'old':'even';
                ?>
                    <tr class='<?php echo $class;?>'>
                        <td>
                            <?php echo $val['id'];?>
                        </td>
                        <td class=''>
                            <a style="color:#000000;" href="<?php echo $this->url('user/permission-manager', array('action'=>'edit','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="edit-line">
                                <?php echo $val['permission']; ?>
                            </a>
                        </td>
                        <?php $name_resource = \User\Libs\Resource\Model::fromId($val['user_acl_resource_id'])->getResource();?>
                        <td class='hidden-350'><?php echo $name_resource; ?></td>
                        <td class='hidden-480'>
                            <a href="<?php echo $this->url('user/permission-manager', array('action'=>'edit','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="edit-line">
                                <button class="btn btn-danger"> <i class="icon-edit"></i></button>
                            </a>

                            <a href="<?php echo $this->url('user/permission-manager', array('action'=>'delete','id' => $val['id'],'redirect'=>$this->redirect)); ?>" class="delete-line">
                                <button class="btn btn-danger"> <i class="icon-trash"></i></button>
                            </a>
                        </td>
                    </tr>
                    <?php
                    $i++;
                   }
                ?>
                </tbody>
            </table>
                <?php echo $this->paginationControl($this->paginator,
                    'Sliding',
                    'layout/system/paginator', array('route' => 'user/permission-manager'));
                ?>
        </div>
    </div>
</div>